name: Publish NuGet Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release

      - name: Publish NuGet Package
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./bin/Release/*.nupkg

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: nupkg

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Add NuGet source
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push NuGet Package
        run: nuget push *.nupkg -Source github -SkipDuplicate